dataset:
  train:
    dir_path: data/train
    batch_size: 512
    num_workers: 4
  val:
    dir_path: data/val
    batch_size: 512
    num_workers: 4
  test:
    dir_path: data/test
    batch_size: 512
    num_workers: 4

train:
  learning_rate: 0.05

pl_trainer: {}
