name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
    - name: Lint with mypy
      run: |
        mypy leela_zero_pytorch --ignore-missing-imports --follow-imports=silent --show-column-numbers
    - name: Code formatting with black
      run: |
        black . --check
    - name: Test with pytest
      run: |
        pytest
